apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  selector:
    app: queue
  ports:
    - containerPort: 5672
      protocol: TCP
    - containerPort: 15672
      protocol: TCP
  type: NodePort
  